[tox]
envlist = linters,update-sources,build,test
skipsdist = true

[testenv]
base_python = 3.12
passenv =
    STREAM
    REGISTRY
    NAMESPACE
    TAG
    IMAGE_PREFIX
    BASE_IMAGE
    CONSTRAINTS_FILE
    BUILD_CONSTRAINTS_FILE
    DEFAULT_STREAM
    SKIP_HASH_UPDATE
    PIP_NO_BINARY
    REGISTRY_AUTH_FILE
    PARALLEL
    BUILD_LOGS_DIR
    UPDATE_LOCKFILES_TARGETS
# pin to pip==26.1.2 as 26.2 has broken pip-tools
deps =
    pip-tools
    pybuild-deps
    pip==26.1.2
allowlist_externals =
    bash

[testenv:linters]
description = Lint all Containerfiles with pre-commit (hadolint)
deps =
    pre-commit>=3.0.0
commands =
    pre-commit run --all-files --show-diff-on-failure {posargs}

[testenv:update-sources]
commands =
    bash -c "rm -f ~/.cache/pybuild-deps/find-build-deps"
    bash {toxinidir}/build.sh update-sources {posargs:all}

[testenv:update-lockfiles]
setenv =
    SKIP_HASH_UPDATE = 1
commands =
    bash -c "rm -f ~/.cache/pybuild-deps/find-build-deps"
    bash {toxinidir}/build.sh update-sources {posargs:all}

[testenv:build]
commands =
    bash {toxinidir}/build.sh build all

[testenv:test]
deps =
    {[testenv]deps}
    ansible-core>=2.18
commands =
    bash {toxinidir}/tests/test_update_sources.sh
    bash {toxinidir}/tests/test_s2i_build_role.sh

[testenv:custom]
commands =
    bash {toxinidir}/build.sh {posargs}
